### ISSUE TITLE
Holes in the barrier in The Bridge

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/maps#1]

**Comment by Gael-de-Sailly** [comment]
![screenshot_20181114_233149](https://user-images.githubusercontent.com/6905002/48517106-8e355180-e865-11e8-8c17-ca58602849b2.png)
Like this one?
I loaded the map using WorldEdit, and these holes are grass or flowers that are replaced by air by CTF.

**Comment by ClobberXD** [comment]
Wrong repo - the schem is in the main repo. ;)

**Comment by ClobberXD** [comment]
All maps including 2H2L and Bridge has been moved to this repo now. So this is indeed the correct repo, but the schem of Bridge is the updated version with the fixed barrier holes.
