### ISSUE TITLE
New Map

### ISSUE THREAD

**Issue by Avyukt1** [MT-CTF/maps#132]
I have map a new map for Minetest CTF Server.
Check out [my map](https://github.com/Avyukt1/Lava-Puddles-Map.git) !

**Comment by Avyukt1** [comment]
Please tell me how test the game on ctf

**Comment by JostP** [comment]
https://github.com/MT-CTF/capturetheflag/
Download code and put it in .minetest/games

**Comment by Avyukt1** [comment]
yes done with that
what next?

**Comment by JostP** [comment]
open minetest
create new game
choose CTF and singlenode mapgen

**Comment by JostP** [comment]
put your map in .minetest/games/capturetheflag/mods/ctf/ctf_map/ctf_map_core/maps where other maps are

**Comment by Avyukt1** [comment]
what
> choose CTF and singlenode mapgen

**Comment by Avyukt1** [comment]
done with adding the map to the folder

**Comment by Avyukt1** [comment]
I can't play it,
It shows an erroe

**Comment by JostP** [comment]
screenshot?

**Comment by Avyukt1** [comment]
https://ibb.co/c6fktjR
is the link of the screenshot

**Comment by Avyukt1** [comment]
@JostP Unable to see "single node mapgen" when I open minetest --> create new game --> choose CTF and singlenode mapgen.

I get these options -> 
v7
valleys
carpathians
v5
flat

Let me what I am missing?

**Comment by Avyukt1** [comment]
@JostP I could see the "single node mapgen" after I scrolled through to the list below. Problem solved, ctf is working and have added my map for testing.

Thank you for all your help.

**Comment by JostP** [comment]
Try to download hame from here: https://content.minetest.net/packages/rubenwardy/capturetheflag/

**Comment by Avyukt1** [comment]
yeah,
It worked

**Comment by JostP** [comment]
So did your map work?

**Comment by Avyukt1** [comment]
Yeah!
But the problem is that the flags spawn position in not on the place where is placed my flags!

**Comment by xenonca** [comment]
Whatsoever, I think this issue can be closed right? Would possibly be better to discuss this elsewhere.

**Comment by Avyukt1** [comment]
There is a problem in the map maker software in my laptop.

**Comment by Avyukt1** [comment]
There is an invisible barrier and the flags are not on the position I placed them
