### ISSUE TITLE
Middle Barrier Alignment

### ISSUE THREAD

**Issue by xenonca** [MT-CTF/maps#157]
> You need to select Z=0 while placing the barriers.
> If you do X=0, you will get wrong initials of the bases and the barrier will be crashed.

_Originally posted by @Avyukt1 in https://github.com/MT-CTF/maps/issues/124#issuecomment-723125866_

I don't think that it matters if you place the middle barrier along the Z or the X axis, I mean that's why you have a choice. However I've tried to export a map too short time ago and the middle barrier wouldn't change direction, no matter which axis I selected.

**Comment by Avyukt1** [comment]
Maybe you should add this issue in the [MT-CTF/capturetheflag](https://github.com/MT-CTF/capturetheflag) to make changes in the `ctf_map` mod.

**Comment by savilli** [comment]
Fixed in V3
