### ISSUE TITLE
Reviewers

### ISSUE THREAD

**Issue by Avyukt1** [MT-CTF/maps#163]
There is a long story what happened with me. The Reviewers of https://github.com/MT-CTF/maps/ are not doing things fairly.
There was partiality (idk It can be laziness). Your maps reviewers are not checking all the maps. This is not accepted at all!

**Comment by JostP** [comment]
We review the longest opened new maps first. Do not interfere in map reviewers work.

**Comment by Avyukt1** [comment]
> We review the longest opened new maps first. Do not interfere in map reviewers work.

@JostP 
of course you will be against this but truth has to be told!

**Comment by Avyukt1** [comment]
Maps reviewing shouldn't be optional.

**Comment by Avyukt1** [comment]
Simply reopen this issue!

**Comment by Avyukt1** [comment]
@JostP 
I am against your partiality or laziness!
And I have the right to create issues against the owner of the repository too!
You are really partial and I will oppose this.
