### ISSUE TITLE
abandoned battlefield have no license, should disable or even remove until a proper license provided

### ISSUE THREAD

**Issue by Emojigit** [MT-CTF/maps#227]

**Comment by Panquesito7** [comment]
That's not correct, the map **does** have a license, as you can see below.

https://github.com/MT-CTF/maps/blob/6afcf12e1ca22873fc4066b242f57b8398131745/abandoned_battlefield/map.conf#L13

**Comment by Emojigit** [comment]
> That's not correct, the map **does** have a license, as you can see below.
> 
> https://github.com/MT-CTF/maps/blob/6afcf12e1ca22873fc4066b242f57b8398131745/abandoned_battlefield/map.conf#L13

sorry
