### ISSUE TITLE
Make "river valley" and "forest" maps more fun for playing

### ISSUE THREAD

**Issue by JostP** [MT-CTF/maps#34]
I think "river valley" and "forest" maps should be improved because they are sometimes quite boring. Anyone can help me do this or give me an idea or suggestion. I guess I will add some buildings etc.

**Comment by LoneWolfHT** [comment]
Ruins or building would be neat to see. But it is pretty fun already IMO

**Comment by ClobberXD** [comment]
Is this still a valid issue? If so, I'd suggest also looking into custom treasures - it's a great way to make the gameplay very interesting, without too many changes.

**Comment by JostP** [comment]
I was thinking about adding custom chest zones first bc there is not enough chests IMO. Adding custom treasures is good idea too.

**Comment by samuelstegerKOLLEGAH** [comment]
I suggest to make something underearth because once me made kinda a huge tunnel all through the way from the big cave to blues base it was kinda fun to play (River Valley I mean) ... And Forrest is okay I think...

**Comment by JostP** [comment]
Closing
