### ISSUE TITLE
Tunnel is very griefer friendly

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/maps#38]
Due to the tunnel of `Tunnel` map being indestructible, sabotagers can block the tunnel and the players are stuck mining out. This can take a lot of time especially if the material is wood.

This can also hurt the person who is coming to their base after capturing the flag of the other team as the griefers can block their way giving time to the other team to kill the person

EDIT: Tagging the map creator to the conversation. @JostP

**Comment by LoneWolfHT** [comment]
it would be nice if you could somehow prevent players from placing anything in the tunnel, it would make the map more interesting

**Comment by ClobberXD** [comment]
We already have mese picks to make digging stone and cobbles much quicker. The problem lies with the availability of wooden planks and team doors in treasure chests. We could try and remove these by implementing per-map treasures.

(We do also have gravel here and there - should we add also a mese shovel to `initial_items`?)

**Comment by LoneWolfHT** [comment]
Things like gravel and wood are only good because they take a while to dig. If we just prevented players from interacting with the tunnel (invisible, non-walkable, non-pointable nodes placed all along the insides of the tunnel)

**Comment by ClobberXD** [comment]
That would prevent strategies like multiple tunnels, though.

**Comment by LoneWolfHT** [comment]
> That would prevent strategies like multiple tunnels, though.

![image](https://user-images.githubusercontent.com/28972859/61191815-8e3f5880-a663-11e9-82b6-7b00f7fad6d2.png)

I'm talking about the tunnels marked with the red lines, the no-interact nodes would be placed only upon the stonebrick. Maybe even in air when in a full 360 part of the tunnel

**Comment by MinetestSam** [comment]
We probably can create a node with transparent textures and make it indestructible and walkable = false should do the job.

**Comment by LoneWolfHT** [comment]
> We probably can create a node with transparent textures and make it indestructible and walkable = false should do the job.

I think an airlike would work. That would save creating a texture too

**Comment by Thomas--S** [comment]
There's already a suitable node for this: `doors:hidden`.

**Comment by ClobberXD** [comment]
> the no-interact nodes would be placed only upon the stonebrick, on the inside of the tunnel

So you're proposing to add a lining to the ind. stone bricks on the inside, with a node that isn't pointable or walkable?

**Comment by LoneWolfHT** [comment]
> > the no-interact nodes would be placed only upon the stonebrick, on the inside of the tunnel
> 
> So you're proposing to add a lining to the ind. stone bricks on the inside, with a node that isn't pointable or walkable?

Yes

**Comment by MinetestSam** [comment]
I like the idea of the base being shifted to where the two red lines are intersecting. This provides a lot of options to the attacking team and also should reduce the damage caused by griefers as player capturing would have multiple sides to come from.

**Comment by ClobberXD** [comment]
> I like the idea of the base being shifted to where the two red lines are intersecting.

That's what I'd prefer too, tbh. The unwalkable, unpointable, invisible nodes would complicate things a lot.

**Comment by JostP** [comment]
I can do this, if you want. Should we move chest room to place where base currently is?

**Comment by ClobberXD** [comment]
Yes, that'd be great. But please make the new chest room as large as the old one. So basically, the base would be moved forward to the 4-way intersection, while the chest room would be centred behind the base.

**Comment by MinetestSam** [comment]
Enhancement PR (#41) made.
