### ISSUE TITLE
License of old maps

### ISSUE THREAD

**Issue by Thomas--S** [MT-CTF/maps#47]
Many of the map files don't have a license added in their `.conf` file.

I strongly suggest to add an appropriate license to all maps.

I think we should only merge new maps if a valid license is stated in the `.conf` file.

CC BY-SA 4.0 might be a good idea for most maps, I think.

Please note: I am not a lawyer.

I ask all map creators to either submit a PR with the change in their `.conf` files or to state in this discussion what license they want to use so that the map team can edit the files.

We'd need an answer from the following map creators:

@rubenwardy 
@ClobberXD 
[WHYjustbecause](https://forum.minetest.net/memberlist.php?mode=viewprofile&u=19630)
@xenonca 
@JostP

**Comment by ClobberXD** [comment]
I'm fine with CC BY-SA 4.0 for IceAge

**Comment by rubenwardy** [comment]
CC BY-SA 4.0 is good by me

**Comment by JostP** [comment]
CC BY-SA 4.0 for my maps

**Comment by ClobberXD** [comment]
We should enforce a fallback license (CC BY-SA 4.0, for example) for maps that don't explicitly specify a license.

**Comment by Thomas--S** [comment]
I am not a lawyer, but I doubt if this was sufficient.

For example, it is theoretically possible to create a map without using the map maker GUI, so the information about the fallback license would be missed.

Instead, I suggest to add a input field for licenses to the map maker GUI, so most maps that are submitted will automatically have an appropriate license.

**Comment by ClobberXD** [comment]
That's exactly what I suggested. A license field should be added, but there should also be an explicit mention of the fact that if no license is specified, CC BY-SA 4.0 is assumed.

**Comment by Thomas--S** [comment]
I simply suggest to only enable the export feature of the map maker GUI as soon as a license is specified. This way we "force" the map maker to actively choose a license.

I think that the license choice should be an active decision by the map maker and no fallback should be assumed.

**Comment by ClobberXD** [comment]
Oh nice, I like your idea better.

**Comment by xenonca** [comment]
CC BY-SA 4.0 is ok for Swamplands and Ancient Pyramids too

**Comment by ClobberXD** [comment]
@xenonca "Ancient Pyramids" hasn't been merged yet, so please add `license = CC BY-SA 4.0` to the map's conf file.

**Comment by Thomas--S** [comment]
#49
