### ISSUE TITLE
Fix missing barriers underwater on older maps

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/maps#71]
Should be pretty simple.

Maps confirmed to be affected by this bug:

- Two hills and two lakes
- Bridge

Maps that are _probably_ affected by this bug:

- Plains of the past
- Coast of nostalgia

**Comment by JostP** [comment]
see PR #76

**Comment by ClobberXD** [comment]
The issue is valid until the PR is merged.

**Comment by JostP** [comment]
Ah ok, sorry
