### ISSUE TITLE
Revert door-removing commits

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/maps#84]
Wooden doors in maps are supported after https://github.com/MT-CTF/capturetheflag/commit/05fba3f5cee7f1064b3ffe7a8760f609f8e769ac.

Note: Reverting the door-removing commits isn't as straight-forward as it might seem, especially if the schem was modified again. Or so I think...

**Comment by Thomas--S** [comment]
I guess it might be the best solution to manually place the doors again while manually comparing the map to an older version.
