### ISSUE TITLE
The Maze is impossible

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/maps#86]

**Comment by ClobberXD** [comment]
Hello, and welcome to GitHub. Usually, an issue description is essential to understand the issue more clearly. Please add an issue description regarding what part of "The Maze" is impossible. And no, "all of it" isn't clear enough.

**Comment by ClobberXD** [comment]
Unable to contact issue author. But I understand why Maze is considered to be "impossible". I'm thinking we disable the map for v2, and the re-enable it when at least some of the issues are fixed.

**Comment by Zipitque** [comment]
It might be easy for new players if they know how to ( Follow the violot path)

**Comment by ClobberXD** [comment]
Finding the way to the enemy base isn't the issue here, from what I can understand; these are:

- There's only one single path to the enemy base, and so this map is functionally identical to a single tunnel.
- If in case a player wanders off the violet path, it's very difficult to get back to the path or to the base.

**Comment by Zipitque** [comment]
Sorry I did not understand the issue.

-

**Comment by ClobberXD** [comment]
Map has been disabled for now. If Waterbug isn't interested in fixing this or no one's willing to take it up, I'm thinking we delete the map after a couple of months.

**Comment by rubenwardy** [comment]
I dislike how vertical this map is, and how regular (ie: it matches a grid exactly)

I'd prefer a more traditional labyrinth-like map, with much less vertical use. You could arrange the labyrinth to have multiple convergence points
