### ISSUE TITLE
Remove class items from map initial items

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/maps#87]
rockets and rifles

**Comment by ClobberXD** [comment]
Maps' initial items dictate the suggested play-style of the map. Also, modifying initial items based on classes doesn't sound very logical IMO, as new maps or new classes would mean having to do this again.

A possibly better solution is to make classes depend on `give_initial_items` mod, and re-write the `give_initial_items` function to omit a map's initial stuff if the player's class already provides it. Should be pretty easy.
