### ISSUE TITLE
Karsthafen town and bridge are identical

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/maps#93]
I've felt this numerous times myself, and most other players feel the same thing. Karsthafen town and Karsthafen bridge are way too similar to each other. The map regions literally overlap each other in the original Karsthafen world, and can be easily noticed while playing - I myself have gotten confused because of this, take my usual path, and end up hundreds of nodes from both bases before realising that this isn't the other Karsthafen map.

CTF maps should offer varied paces and styles of gameplay, and the two Karsthafen maps in question violate this principle. I'm all for removing either one of the violating maps. Feel free to discuss which one could be removed, and/or maybe provide alternatives to removing the maps.

I'd ideally prefer to resolve this issue before the great grand release of CTF v2.0, but after release is fine by me too, if that's what it comes down to.

**Comment by JostP** [comment]
I agree that they are too similar to each other. I'm fine with removing one of them.

**Comment by ClobberXD** [comment]
Good choice. Now onto discussing *which* one of the two should be removed.

What are the pros and cons of both maps? As the Karsthafen maps are based on a "city" theme, I'd suggesting removing the one that has less "city"-like environment and has more natural terrain.

**Comment by JostP** [comment]
I think bridge one has less "city". I will test both maps once today.
